travis:
  secure:
    BINSTAR_TOKEN: AqF10b7NzYPdKOsXbiY3ok2EoekyqnoU5KXtpmh7UiDEf3n8z3S7Bn5cG8lFkF1bBn5uefBSLX7wVj9CRNd4BZqbE/xeKEARxEWCJiutaGkjSpIFFCI6ENGUnSmMbOOfJguL/IcN0/shpKkUcmpHFjG95zp9Otiv+TqqqBAtEuL8mcc2DFIxpJywLGfujqADRUYymxgA9y6+R2DFXohaX+dO7ub5P2454H2i0OUd+WfjpvJ7weIUZU6EGTZGewHIdbSD9EPF9s9u0Orm/ZdTNNkO1sqWIYNZpFZNMLhz+Ykq/2kNJAK5NSIjcPNJtCGXDkVWDa9POOO2b+34YzVAdLrZum6ujUYTpxDffC7YnpI7E8E+DS6WXqjFxkg+gd0lCUbsBLj1BPC7+FmomvhnlNc8rdUhDECaASJ1OkQI8BQfL+P3wV8wdA114Rgiii/Y3kiBDnX7B3l9kFGduMBLeH68V/ZZB26NcDCVP/VyVgc51JHRJDTZa4ywUtRLrSio00+KXA1+LGTfuGwvuaEB9PsD0XH0yhMXFqllNjaYKPVYr4yGG0l2IiEOJ8hY9mXWIvwba8zKeB/s9QJqzrK7I7vZsTrhblQb1WWrcqjqbONye8sj54ht3O59enEef2yVZSAWp6r8IMN1dWjxpmgWNMo7usyWzq6SE3BDSpLX6IE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
