travis:
  secure:
    BINSTAR_TOKEN: T5SSbqwScf9GYdp7LF7RtEA/Yez5HqV6z9nVqPQ8Vg/GSfPCI2/DtuEqNfTBR8IW01l77s0Syd5smPZtKEaRQ5AeBpKo59ntWLCgm3ekpYWmkxT51YeH6dV/zo65VJ9GGDKE1u2/0XRMbEOPNzOPLYx2TOGpllWZXA5UAXSC71ampL7wPNnp4nLY6LpVlfvnq5eMtWhQht1PZChRgAAap5Bb0nCr2ZmZTNpzEaIUmvxW0+30EIqem9hVtBSXgcAFhJCf5uPzVPhMnjRooymbB+JdJD0qkyGpC3uhdrk49fbI59b0R/tHgL39g3mWzH5IgtbKepgMe8dKAtS1Sx0dO5QC7znPfL5SLO3j/fRGGI2dLCE1HJNzRv1aREgHZjkChvV5IDF8trIKkykjoHBuaMPwXesE3KnN9smlrcPW4U94KHFTwvHFBKiYsN5JzaqaeypZGdkCsmEttJOKAqms1bGvfD2qY9l0rddMAzBwT1UbiuHolC7RybwYIbfm6bbLgXg5Pj4zH4gul38yUvjikYYIjViCIuGuxqiMAs6AC1UNDRdPZ5B7erg8zPQO8qNjObHnpGfky7lYsNX99NvbjxHUDj4vTnrk1sCDE+cN2FaIGrIMoyqcnvsms4qAb+iilVvDPPOkytrXyjurExdZj+g69GZuMycFdCzgpmuGgKw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
